debug: false

# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------
